name: test deployment
on:
push:
  branches: 
    - "prueba"
jobs:
  build-and-deploy:
      runs-on: ubuntu-lastest
      steps: 
        - name: Checkout
          uses: action/checkout@master
          with:
            persist-credencials: false
        - name: Install and Build
          run: |
            npm install
            npm run build
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@3.7.1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: prueba
            folder: build
